from sqlalchemy import Column, String, Integer, Float, Text, DateTime, JSON
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.sql import func
from uuid import uuid4

from app.backend.database.connection import Base


class Memo(Base):
    """Investment memos generated by AI analysts for human review"""
    __tablename__ = "memos"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid4()))
    ticker = Column(String(10), nullable=False, index=True)
    analyst = Column(String(50), nullable=False, index=True)  # e.g., "warren_buffett"
    signal = Column(String(10), nullable=False)  # "bullish" or "bearish"
    conviction = Column(Integer, nullable=False)  # 0-100
    thesis = Column(Text, nullable=False)
    bull_case = Column(JSON, nullable=False)  # list of 3 strings
    bear_case = Column(JSON, nullable=False)  # list of 3 strings
    metrics = Column(JSON, nullable=False)  # analyst-specific metrics
    current_price = Column(Float, nullable=False)
    target_price = Column(Float, nullable=False)
    time_horizon = Column(String(20), nullable=False)  # "short", "medium", "long"
    status = Column(String(20), default="pending", index=True)  # "pending", "approved", "rejected"
    generated_at = Column(DateTime(timezone=True), nullable=False)
    reviewed_at = Column(DateTime(timezone=True), nullable=True)
